version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build: ./backend
    container_name: backend
    command: gunicorn finances.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend-network

  frontend:
    build: ./frontend
    container_name: frontend
    command: serve -s dist -l 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
